### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by chuheme** [Sakura-Panel/ss-panel-v3-mod-Sakura#1]
I have install it nearly dozens of times according to the Recommend, only user center(/user) can be logined in and reached normally,  HTTP ERROR 500 was returned for the rests of the pages(like user/profile, user/edit and etc. )
I don't know where goes wrong, could you please offer some help or a installation whenever it's convenient.
Thanks.

…And feel very uneasy to disturb you.

**Comment by SakuraSa233** [comment]
The `dev` branch is under rebuilding that is clearly written in topics. Please use the `master` branch for stable performance. The whole project is developed for self-using, please take acknowledge of it.

CI is still in working, so `.travis.yml` have no value to be referenced.

The most important is that **only English** is recommended to use in this repository.

**Comment by chuheme** [comment]
> The `dev` branch is under rebuilding that is clearly written in description. Please use the `master` branch for stable performance. The whole project is developed for self-using, please take acknowledge of it.
> 
> CI is still in working, so `.travis.yml` have no value to be referenced.
> 
> The most important is that **only English** is recommended to use in this repository.

**Comment by chuheme** [comment]
In view of 

> The whole project is developed for self-using
Closed.
